services:
  # Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: arko_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: arko_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend em Go
  backend:
    build: ./backend
    container_name: arko_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      # Garantimos que a pasta de uploads no container seja a mesma da sua m√°quina
      - ./backend/uploads:/app/uploads 
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: arko_db

volumes:
  postgres_data:
