services:
  # O Banco de Dados que o Django normalmente configuraria para vocÃª
  db:
    image: postgres:15-alpine
    container_name: arko_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: arko_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # O Backend em Go (vamos construir a imagem depois)
  backend:
    build: ./backend
    container_name: arko_api
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: arko_db

volumes:
  postgres_data:
